### ISSUE TITLE
DISCUSSION: Do we want to use React + Foundation?

### ISSUE THREAD

**Issue by bluedrops** [ReflectionsProjections/rp2017#22]
Foundation is a responsive front-end framework that comes with many components that have been built and styled and made responsive already by experienced frontend developers. 

React + Foundation is a repackaging of Foundation into React components that we can use pretty easily.

Example:
![](http://i.imgur.com/7hBUkjA.png)

Pros:
- The developers of Foundation are much more skilled at making responsive components than we are
- Less time wasted styling common use-case elements like text fields, text, buttons, info-containers, etc.

Cons:
- Not everyone has experience with Foundation
- I don't want to make the project too beginner-unfriendly.

Overall, I think it could save us a lot of time though.

Thoughts?

https://react.foundation

**Comment by pranaygp** [comment]
React + Foundation seems like a great choice IMO. In the past I've always jumped into using React Bootstrap (which is also amazing, and is what you and I are using for our 242 project, lol 😛  )

Also, added benefit with react bootstrap is that anyone familiar with bootstrap will be able to sue the same bindings they expect with react bootstrap (like `<Col xs={6} md={4} />`)

So that's my vote on the discussion 

p.s. [link to react-bootstrap compnent library](https://react-bootstrap.github.io/components.html)
